In [19]:
()

()

In [20]:
favoritelang = ("Python", "Julia", "R")

("Python", "Julia", "R")

In [21]:
x1 = (1, 2, 3)

(1, 2, 3)

In [22]:
x2 = (1, 2.0, "tmp")

(1, 2.0, "tmp")

In [23]:
x3 = (a=2, b=1+2)

(a = 2, b = 3)

In [24]:
length(x2)

3

In [25]:
x2[1], x2[2], x2[3]

(1, 2.0, "tmp")

In [26]:
c = x1[2] + x1[3]

5

In [27]:
x3.a, x3.b, x3[2]

(2, 3, 3)

In [28]:
in("tmp", x2), 0 in x2

(true, false)

In [29]:
phonebook = Dict(
    "Иванов И.И." => ("867-5309", "333-5544"),
    "Бухгалтерия" => "555-2368"
)

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [30]:
keys(phonebook)

KeySet for a Dict{String, Any} with 2 entries. Keys:
  "Бухгалтерия"
  "Иванов И.И."

In [31]:
values(phonebook)

ValueIterator for a Dict{String, Any} with 2 entries. Values:
  "555-2368"
  ("867-5309", "333-5544")

In [32]:
pairs(phonebook)

Dict{String, Any} with 2 entries:
  "Бухгалтерия" => "555-2368"
  "Иванов И.И." => ("867-5309", "333-5544")

In [33]:
haskey(phonebook, "Иванов И.И.")

true

In [34]:
phonebook["Сидоров П.С."] = "555-3344"

"555-3344"

In [35]:
pop!(phonebook, "Иванов И.И.")

("867-5309", "333-5544")

In [36]:
a = Dict("foo" => 0.0, "bar" => 42.0);
b = Dict("baz" => 17, "bar" => 13.0);
merge(a, b), merge(b, a)

(Dict{String, Real}("bar" => 13.0, "baz" => 17, "foo" => 0.0), Dict{String, Real}("bar" => 42.0, "baz" => 17, "foo" => 0.0))

In [37]:
A = Set([1, 3, 4, 5])

Set{Int64} with 4 elements:
  5
  4
  3
  1

In [38]:
B = Set("abrakadabra")

Set{Char} with 5 elements:
  'a'
  'd'
  'r'
  'k'
  'b'

In [39]:
S1 = Set([1, 2])
S2 = Set([3, 4])
issetequal(S1, S2)

false

In [40]:
S3 = Set([1, 2, 2, 3, 1, 2, 3, 2, 1])
S4 = Set([2, 3, 1])
issetequal(S3, S4)

true

In [43]:
C = union(S1, S2)

Set{Int64} with 4 elements:
  4
  2
  3
  1

In [44]:
D = intersect(S1, S3)

Set{Int64} with 2 elements:
  2
  1

In [45]:
E = setdiff(S3, S1)

Set{Int64} with 1 element:
  3

In [46]:
issubset(S1, S4)

true

In [47]:
push!(S4, 99)

Set{Int64} with 4 elements:
  2
  99
  3
  1

In [48]:
pop!(S4)

2

In [49]:
empty_array = []

Any[]

In [52]:
empty_array_2 = (Int64)[]

Int64[]

In [53]:
empty_array_3 = (Float64)[]

Float64[]

In [54]:
a = [1, 2, 3]

3-element Vector{Int64}:
 1
 2
 3

In [55]:
b = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [56]:
A = [[1, 2, 3] [4, 5, 6] [7, 8, 9]]

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  9

In [57]:
B = [[1 2 3]; [4 5 6]; [7 8 9]]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [58]:
c = rand(1, 8)

1×8 Matrix{Float64}:
 0.16822  0.278178  0.0879463  0.485416  …  0.777814  0.829817  0.897611

In [59]:
C = rand(2, 3)

2×3 Matrix{Float64}:
 0.187428  0.538214  0.875849
 0.851585  0.472582  0.795135

In [62]:
D = rand(4, 3, 2)

4×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.272256   0.638178  0.10435
 0.495959   0.83931   0.845109
 0.0489139  0.141009  0.416999
 0.315541   0.636198  0.140045

[:, :, 2] =
 0.576745  0.00782045  0.179376
 0.854092  0.799871    0.257626
 0.46979   0.694563    0.537992
 0.465904  0.674004    0.334386

In [63]:
roots = [sqrt(i) for i in 1:10]

10-element Vector{Float64}:
 1.0
 1.4142135623730951
 1.7320508075688772
 2.0
 2.23606797749979
 2.449489742783178
 2.6457513110645907
 2.8284271247461903
 3.0
 3.1622776601683795

In [64]:
ar_1 = [3*i^2 for i in 1:2:9]

5-element Vector{Int64}:
   3
  27
  75
 147
 243

In [65]:
ar_2 = [i^2 for i=1:10 if (i^2%5!=0 && i^2%4!=0)]

4-element Vector{Int64}:
  1
  9
 49
 81

In [66]:
ones(5)

5-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0
 1.0

In [67]:
ones(2, 3)

2×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0

In [68]:
zeros(4)

4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.0

In [69]:
fill(3.5, (3, 2))

3×2 Matrix{Float64}:
 3.5  3.5
 3.5  3.5
 3.5  3.5

In [70]:
repeat([1, 2], 3, 3)

6×3 Matrix{Int64}:
 1  1  1
 2  2  2
 1  1  1
 2  2  2
 1  1  1
 2  2  2

In [71]:
repeat([1 2], 3, 3)

3×6 Matrix{Int64}:
 1  2  1  2  1  2
 1  2  1  2  1  2
 1  2  1  2  1  2

In [72]:
a = collect(1:12)

12-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12

In [73]:
b = reshape(a, (2, 6))

2×6 Matrix{Int64}:
 1  3  5  7   9  11
 2  4  6  8  10  12

In [74]:
b'

6×2 adjoint(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [75]:
c = transpose(b)

6×2 transpose(::Matrix{Int64}) with eltype Int64:
  1   2
  3   4
  5   6
  7   8
  9  10
 11  12

In [76]:
ar = rand(10:20, 10, 5)

10×5 Matrix{Int64}:
 17  15  17  12  10
 16  10  20  14  12
 16  13  19  16  10
 16  18  10  10  10
 16  16  15  17  15
 17  10  11  10  18
 19  13  10  14  11
 16  13  20  16  10
 14  13  10  18  18
 11  16  15  19  17

In [77]:
ar[:, 2]

10-element Vector{Int64}:
 15
 10
 13
 18
 16
 10
 13
 13
 13
 16

In [78]:
ar[:, [2, 5]]

10×2 Matrix{Int64}:
 15  10
 10  12
 13  10
 18  10
 16  15
 10  18
 13  11
 13  10
 13  18
 16  17

In [80]:
ar[:, 2:4]

10×3 Matrix{Int64}:
 15  17  12
 10  20  14
 13  19  16
 18  10  10
 16  15  17
 10  11  10
 13  10  14
 13  20  16
 13  10  18
 16  15  19

In [81]:
ar[[2, 4, 6], [1, 5]]

3×2 Matrix{Int64}:
 16  12
 16  10
 17  18

In [82]:
ar[1, 3:end]

3-element Vector{Int64}:
 17
 12
 10

In [83]:
sort(ar, dims=1)

10×5 Matrix{Int64}:
 11  10  10  10  10
 14  10  10  10  10
 16  13  10  12  10
 16  13  11  14  10
 16  13  15  14  11
 16  13  15  16  12
 16  15  17  16  15
 17  16  19  17  17
 17  16  20  18  18
 19  18  20  19  18

In [84]:
sort(ar, dims=2)

10×5 Matrix{Int64}:
 10  12  15  17  17
 10  12  14  16  20
 10  13  16  16  19
 10  10  10  16  18
 15  15  16  16  17
 10  10  11  17  18
 10  11  13  14  19
 10  13  16  16  20
 10  13  14  18  18
 11  15  16  17  19

In [85]:
ar .> 14

10×5 BitMatrix:
 1  1  1  0  0
 1  0  1  0  0
 1  0  1  1  0
 1  1  0  0  0
 1  1  1  1  1
 1  0  0  0  1
 1  0  0  0  0
 1  0  1  1  0
 0  0  0  1  1
 0  1  1  1  1

In [86]:
findall(ar .> 14)

27-element Vector{CartesianIndex{2}}:
 CartesianIndex(1, 1)
 CartesianIndex(2, 1)
 CartesianIndex(3, 1)
 CartesianIndex(4, 1)
 CartesianIndex(5, 1)
 CartesianIndex(6, 1)
 CartesianIndex(7, 1)
 CartesianIndex(8, 1)
 CartesianIndex(1, 2)
 CartesianIndex(4, 2)
 CartesianIndex(5, 2)
 CartesianIndex(10, 2)
 CartesianIndex(1, 3)
 ⋮
 CartesianIndex(5, 3)
 CartesianIndex(8, 3)
 CartesianIndex(10, 3)
 CartesianIndex(3, 4)
 CartesianIndex(5, 4)
 CartesianIndex(8, 4)
 CartesianIndex(9, 4)
 CartesianIndex(10, 4)
 CartesianIndex(5, 5)
 CartesianIndex(6, 5)
 CartesianIndex(9, 5)
 CartesianIndex(10, 5)

In [88]:
A = Set([0, 3, 4, 9])
B = Set([1, 3, 4, 7])
C = Set([0, 1, 2, 4, 7, 8, 9])
P = intersect(union(A, B), union(A, B), union(A, C), union(B, C))

Set{Int64} with 6 elements:
  0
  4
  7
  9
  3
  1

In [99]:
aaa = (12, 13, 14); bbb = [444, 4421, 3456]
length(aaa)

3

In [100]:
ccc = [aaa[end], pop!(bbb), "RRR"]

3-element Vector{Any}:
   14
 3456
     "RRR"

In [102]:
ddd = [i for i in ccc]

3-element Vector{Any}:
   14
 3456
     "RRR"

In [110]:
ar = [i for i in 1:21]
print(ar)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21]

In [108]:
ar = reverse([i for i in 1:21])
print(ar)

[21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [109]:
ar = [i for i in 21:-1:1]
print(ar)

[21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [117]:
ar = vcat(1:21, 20:-1:1)
print(ar)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

In [119]:
tmp = [4 6 3]
print(tmp)

[4 6 3]

In [123]:
ar = vcat([tmp[1] for _ in 1:10], tmp[2:end])
print(ar)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 3]

In [127]:
ar = vcat([tmp[1] for _ in 1:10], [tmp[2] for _ in 1:10],
    [tmp[3] for _ in 1:10])
print(ar)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

In [128]:
ar = vcat([tmp[1] for _ in 1:11], [tmp[2] for _ in 1:10],
    [tmp[3] for _ in 1:10])
print(ar)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

In [129]:
ar = vcat([tmp[1] for _ in 1:10], [tmp[2] for _ in 1:20],
    [tmp[3] for _ in 1:30])
print(ar)

[4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]

In [157]:
tmp = [4 6 3]
ar = []
for i in tmp
    push!(ar, 2^i)
end
ar = vcat(ar[1:2], [ar[3] for _ in 1:4])
ar = string.(ar)
ar = join(ar, "")
counter = count(isequal('6'), ar)
print(counter)

2

In [178]:
y(x) = exp(x)*cos(x)
Y = [y(x) for x in 3:0.1:6]
mean = sum(Y) / length(Y)

53.11374594642971

In [179]:
vect = []
for j in 1:3:34
    i = j + 2
    push!(vect, (0.1^i, 0.2^j))
end
print(vect)

Any[(0.0010000000000000002, 0.2), (1.0000000000000004e-6, 0.0016000000000000003), (1.0000000000000005e-9, 1.2800000000000005e-5), (1.0000000000000006e-12, 1.0240000000000006e-7), (1.0000000000000009e-15, 8.192000000000005e-10), (1.000000000000001e-18, 6.5536000000000055e-12), (1.0000000000000012e-21, 5.2428800000000056e-14), (1.0000000000000014e-24, 4.194304000000005e-16), (1.0000000000000015e-27, 3.3554432000000048e-18), (1.0000000000000017e-30, 2.684354560000004e-20), (1.0000000000000018e-33, 2.1474836480000035e-22), (1.000000000000002e-36, 1.717986918400003e-24)]

In [180]:
vect = []
for i in 1:25
    push!(vect, (2^i)/i)
end
print(vect)

Any[2.0, 2.0, 2.6666666666666665, 4.0, 6.4, 10.666666666666666, 18.285714285714285, 32.0, 56.888888888888886, 102.4, 186.1818181818182, 341.3333333333333, 630.1538461538462, 1170.2857142857142, 2184.5333333333333, 4096.0, 7710.117647058823, 14563.555555555555, 27594.105263157893, 52428.8, 99864.38095238095, 190650.18181818182, 364722.0869565217, 699050.6666666666, 1.34217728e6]

In [181]:
vect = []
for i in 1:30
    push!(vect, "fn$i")
end
print(vect)

Any["fn1", "fn2", "fn3", "fn4", "fn5", "fn6", "fn7", "fn8", "fn9", "fn10", "fn11", "fn12", "fn13", "fn14", "fn15", "fn16", "fn17", "fn18", "fn19", "fn20", "fn21", "fn22", "fn23", "fn24", "fn25", "fn26", "fn27", "fn28", "fn29", "fn30"]