In [1]:
n = 0
while n < 10
    n += 1
    println(n)
end

1
2
3
4
5
6
7
8
9
10


In [1]:
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]
i = 1
while i <= length(myfriends)
    friend = myfriends[i]
    println("Hi $friend, it's great to see you!")
    i += 1
end

Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [3]:
for n in 1:2:10
    println(n)
end
myfriends = ["Ted", "Robyn", "Barney", "Lily", "Marshall"]
for friend in myfriends
    println("Hi $friend, it's great to see you!")
end

1
3
5
7
9
Hi Ted, it's great to see you!
Hi Robyn, it's great to see you!
Hi Barney, it's great to see you!
Hi Lily, it's great to see you!
Hi Marshall, it's great to see you!


In [4]:
m, n = 5, 5
A = fill(0, (m, n))
for i in 1:m
    for j in 1:n
        A[i, j] = i + j
    end
end
A

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [5]:
B = fill(0, (m, n))
for i in 1:m, j in 1:n
    B[i, j] = i + j
end
B

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [6]:
C = [i + j for i in 1:m, j in 1:n]
C

5×5 Matrix{Int64}:
 2  3  4  5   6
 3  4  5  6   7
 4  5  6  7   8
 5  6  7  8   9
 6  7  8  9  10

In [10]:
N = 10
if (N % 3 == 0) && (N % 5 == 0)
    println("FizzBuzz")
elseif N % 3 == 0
    println("Fizz")
elseif N % 5 == 0
    println("Buzz")
else
    println(N)
end

Buzz


In [11]:
x = 5
y = 10
(x > y) ? x : y

10

In [13]:
function sayhi(name)
    println("Hi $name, it's great to see you!")
end

function f(x)
    x^2
end

sayhi("C-3PO")
f(42)

Hi C-3PO, it's great to see you!


1764

In [14]:
sayhi2(name) = println("Hi $name, it's great to see you!")
f2(x) = x^2

f2 (generic function with 1 method)

In [15]:
sayhi3 = name -> println("Hi $name, it's great to see you!")
f3 = x -> x2

#5 (generic function with 1 method)

In [18]:
v = [3, 5, 2]
sort(v)
print(v)
sort!(v)
print(v)

[3, 5, 2][2, 3, 5]

In [19]:
f(x) = x^2
map(f, [1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [20]:
map(x -> x^3, [1, 2, 3])

3-element Vector{Int64}:
  1
  8
 27

In [21]:
f(x) = x^2
broadcast(f, [1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [22]:
f.([1, 2, 3])

3-element Vector{Int64}:
 1
 4
 9

In [23]:
A = [i + 3*j for j in 0:2, i in 1:3]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [24]:
f(A)

3×3 Matrix{Int64}:
  30   36   42
  66   81   96
 102  126  150

In [25]:
B = f.(A)

3×3 Matrix{Int64}:
  1   4   9
 16  25  36
 49  64  81

In [27]:
A .+ 2 .* f.(A) ./ A

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [28]:
@. A + 2 * f(A) / A

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [29]:
broadcast(x -> x + 2 * f(x) / x, A)

3×3 Matrix{Float64}:
  3.0   6.0   9.0
 12.0  15.0  18.0
 21.0  24.0  27.0

In [31]:
import Pkg
Pkg.add("Colors")

   Resolving package versions...
  No Changes to `~/.julia/environments/v1.11/Project.toml`
  No Changes to `~/.julia/environments/v1.11/Manifest.toml`


In [32]:
using Colors
palette = distinguishable_colors(1000)

In [33]:
rand(palette, 3, 3)

In [36]:
for i in 1:100
    print(i, ": ", i^2, ";;; ")
end

1: 1;;; 2: 4;;; 3: 9;;; 4: 16;;; 5: 25;;; 6: 36;;; 7: 49;;; 8: 64;;; 9: 81;;; 10: 100;;; 11: 121;;; 12: 144;;; 13: 169;;; 14: 196;;; 15: 225;;; 16: 256;;; 17: 289;;; 18: 324;;; 19: 361;;; 20: 400;;; 21: 441;;; 22: 484;;; 23: 529;;; 24: 576;;; 25: 625;;; 26: 676;;; 27: 729;;; 28: 784;;; 29: 841;;; 30: 900;;; 31: 961;;; 32: 1024;;; 33: 1089;;; 34: 1156;;; 35: 1225;;; 36: 1296;;; 37: 1369;;; 38: 1444;;; 39: 1521;;; 40: 1600;;; 41: 1681;;; 42: 1764;;; 43: 1849;;; 44: 1936;;; 45: 2025;;; 46: 2116;;; 47: 2209;;; 48: 2304;;; 49: 2401;;; 50: 2500;;; 51: 2601;;; 52: 2704;;; 53: 2809;;; 54: 2916;;; 55: 3025;;; 56: 3136;;; 57: 3249;;; 58: 3364;;; 59: 3481;;; 60: 3600;;; 61: 3721;;; 62: 3844;;; 63: 3969;;; 64: 4096;;; 65: 4225;;; 66: 4356;;; 67: 4489;;; 68: 4624;;; 69: 4761;;; 70: 4900;;; 71: 5041;;; 72: 5184;;; 73: 5329;;; 74: 5476;;; 75: 5625;;; 76: 5776;;; 77: 5929;;; 78: 6084;;; 79: 6241;;; 80: 6400;;; 81: 6561;;; 82: 6724;;; 83: 6889;;; 84: 7056;;; 85: 7225;;; 86: 7396;;; 87: 7569;;; 88: 7744

In [37]:
squares = Dict()
for i in 1:5
    squares[i] =i^2
end
print(squares)

Dict{Any, Any}(5 => 25, 4 => 16, 2 => 4, 3 => 9, 1 => 1)

In [38]:
squares_arr = [i^2 for i in 1:100]
print(squares_arr)

[1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144, 169, 196, 225, 256, 289, 324, 361, 400, 441, 484, 529, 576, 625, 676, 729, 784, 841, 900, 961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521, 1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401, 2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481, 3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761, 4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241, 6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921, 8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801, 10000]

In [40]:
x = 9
if x % 2 == 0
    println(x)
elseif x % 2 != 0
    println("odd")
end

odd


In [41]:
(x % 2 == 0) ? println(x) : println("odd")

odd


In [43]:
function add_one(x)
    x += 1
    return x
end
add_one!(2)

3

In [47]:
A = fill(0, (3, 3))
broadcast(x -> x+1, A)

3×3 Matrix{Int64}:
 1  1  1
 1  1  1
 1  1  1

In [52]:
A = [1 1 3; 5 2 6; -2 -1 -3]

3×3 Matrix{Int64}:
  1   1   3
  5   2   6
 -2  -1  -3

In [58]:
f(x) = x^3
f.(A)

3×3 Matrix{Int64}:
   1   1   27
 125   8  216
  -8  -1  -27

In [59]:
for i in 1:3
    A[i, 3] = A[i, 1] + A[i, 2]
end
A

3×3 Matrix{Int64}:
  1   1   2
  5   2   7
 -2  -1  -3

In [60]:
B = zeros(15, 3)
for i in 1:15
    B[i, 1] = 10
    B[i, 2] = -10
    B[i, 3] = 10
end
B

15×3 Matrix{Float64}:
 10.0  -10.0  10.0
 10.0  -10.0  10.0
 10.0  -10.0  10.0
 10.0  -10.0  10.0
 10.0  -10.0  10.0
 10.0  -10.0  10.0
 10.0  -10.0  10.0
 10.0  -10.0  10.0
 10.0  -10.0  10.0
 10.0  -10.0  10.0
 10.0  -10.0  10.0
 10.0  -10.0  10.0
 10.0  -10.0  10.0
 10.0  -10.0  10.0
 10.0  -10.0  10.0

In [61]:
C = B' * B

3×3 Matrix{Float64}:
  1500.0  -1500.0   1500.0
 -1500.0   1500.0  -1500.0
  1500.0  -1500.0   1500.0

In [65]:
Z = fill(0, (6, 6))
E = fill(1, (6, 6))
Z1, Z2, Z3, Z4 = copy(Z), copy(Z), copy(Z), copy(Z)
for i in 1:6, j in 1:6
    if j == i - 1 || j == i + 1
        Z1[i, j] = 1
    end
end
for i in 1:6, j in 1:6
    if j == i - 2 || j == i || j == i + 2
        Z2[i, j] = 1
    end
end
for i in 1:6, j in 1:6
    if j == 5 - i || j == 7 - i || j == 9 - i
        Z3[i, j] = 1
    end
end
for i in 1:6, j in 1:6
    if (i + j) % 2 == 0
        Z4[i, j] = 1
    end
end
Z1

6×6 Matrix{Int64}:
 0  1  0  0  0  0
 1  0  1  0  0  0
 0  1  0  1  0  0
 0  0  1  0  1  0
 0  0  0  1  0  1
 0  0  0  0  1  0

In [66]:
Z2

6×6 Matrix{Int64}:
 1  0  1  0  0  0
 0  1  0  1  0  0
 1  0  1  0  1  0
 0  1  0  1  0  1
 0  0  1  0  1  0
 0  0  0  1  0  1

In [67]:
Z3

6×6 Matrix{Int64}:
 0  0  0  1  0  1
 0  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  0
 1  0  1  0  0  0

In [68]:
Z4

6×6 Matrix{Int64}:
 1  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  1
 1  0  1  0  1  0
 0  1  0  1  0  1

In [78]:
function outer(x, y, f)
    if (f == "*")
        res = x .* y'
    elseif (f == "+")
        res = x .+ y'
    elseif (f == "^")
        res = x .^ y'
    elseif (f == "-")
        res = x .- y'
    elseif (f == "%")
        res = x .% y'
    end
end


outer (generic function with 1 method)

In [79]:
A1 = outer(0:4, 0:4, "+")
A1

5×5 Matrix{Int64}:
 0  1  2  3  4
 1  2  3  4  5
 2  3  4  5  6
 3  4  5  6  7
 4  5  6  7  8

In [80]:
A2 = outer(0:4, 1:5, "^")
A2

5×5 Matrix{Int64}:
 0   0   0    0     0
 1   1   1    1     1
 2   4   8   16    32
 3   9  27   81   243
 4  16  64  256  1024

In [81]:
A3 = outer(outer(0:4, 0:4, "+"), 5, "%")

5×5 Matrix{Int64}:
 0  1  2  3  4
 1  2  3  4  0
 2  3  4  0  1
 3  4  0  1  2
 4  0  1  2  3

In [83]:
A4 = outer(outer(0:9, 0:9, "+"), 10, "%")

10×10 Matrix{Int64}:
 0  1  2  3  4  5  6  7  8  9
 1  2  3  4  5  6  7  8  9  0
 2  3  4  5  6  7  8  9  0  1
 3  4  5  6  7  8  9  0  1  2
 4  5  6  7  8  9  0  1  2  3
 5  6  7  8  9  0  1  2  3  4
 6  7  8  9  0  1  2  3  4  5
 7  8  9  0  1  2  3  4  5  6
 8  9  0  1  2  3  4  5  6  7
 9  0  1  2  3  4  5  6  7  8

In [120]:
A5 = outer(1:8, 8:-1:1, "+")
A5 = outer(A5, 9, "%")

8×8 Matrix{Int64}:
 0  8  7  6  5  4  3  2
 1  0  8  7  6  5  4  3
 2  1  0  8  7  6  5  4
 3  2  1  0  8  7  6  5
 4  3  2  1  0  8  7  6
 5  4  3  2  1  0  8  7
 6  5  4  3  2  1  0  8
 7  6  5  4  3  2  1  0

In [124]:
A = [
    1 2 3 4 5;
    2 1 2 3 4;
    3 2 1 2 3;
    4 3 2 1 2;
    5 4 3 2 1
]
y = [7; -1; -3; 5; 17]
x = A \ y

5-element Vector{Float64}:
 -2.0000000000000036
  3.0000000000000058
  4.999999999999998
  1.9999999999999991
 -3.999999999999999

In [126]:
M = rand(1:10, 6, 10)
println(M)
N = 4
sum(M.>N)

[7 7 3 3 1 8 8 3 8 4; 4 9 8 2 6 8 3 5 2 1; 5 3 2 4 7 5 3 4 3 10; 5 5 9 5 2 8 10 9 4 10; 3 3 3 3 9 7 2 1 5 7; 7 9 9 8 2 9 5 5 9 9]


35

In [127]:
[i for i in 1:6 if sum(M[i, :] .== 7) == 2]

2-element Vector{Int64}:
 1
 5

In [128]:
K = 75
[(i, j) for i in 1:6, j in 2:5 if (i != j && sum(M[:, i] + M[:, j]) > K)]

2-element Vector{Tuple{Int64, Int64}}:
 (6, 2)
 (6, 3)

In [131]:
sum1 = sum((i^4)/(3 + j) for i in 1:20, j in 1:5)

639215.2833333338

In [132]:
sum2 = sum((i^4)/(3 + i * j) for i in 1:20, j in 1:5)

89912.02146097131