In [1]:
typeof(3.5)

Float64

In [3]:
for T in [Int8, Int16, Int32, Int64, Int128, UInt8, UInt16, UInt32, UInt64, UInt128]
    println("$(lpad(T,7)): [$(typemin(T)), $(typemax(T))]")
end

   Int8: [-128, 127]
  Int16: [-32768, 32767]
  Int32: [-2147483648, 2147483647]
  Int64: [-9223372036854775808, 9223372036854775807]
 Int128: [-170141183460469231731687303715884105728, 170141183460469231731687303715884105727]
  UInt8: [0, 255]
 UInt16: [0, 65535]
 UInt32: [0, 4294967295]
 UInt64: [0, 18446744073709551615]
UInt128: [0, 340282366920938463463374607431768211455]


In [4]:
Int64(2.0)

2

In [5]:
Char(2)

'\x02': ASCII/Unicode U+0002 (category Cc: Other, control)

In [6]:
convert(Int64, 2.0)

2

In [8]:
promote(Int8(1), Float16(4.5), Float32(4.1))

(1.0f0, 4.5f0, 4.1f0)

In [9]:
typeof(promote(Int8(1), Float16(4.5), Float32(4.1)))

Tuple{Float32, Float32, Float32}

In [10]:
function f(x)
    x^2
end
f(4)

16

In [11]:
g(x)=x^2
g(4)

16

In [12]:
a = [4 7 6]
b = [1, 2, 3]
a[2], b[2]

(7, 2)

In [13]:
a = 1; b = 2; c = 3; d = 4
Am = [a b; c d]

2×2 Matrix{Int64}:
 1  2
 3  4

In [14]:
aa = [1 2]
AA = [1 2; 3 4]
aa*AA*aa'

1×1 Matrix{Int64}:
 27

In [15]:
?read()

```
read(io::IO, T)
```

Read a single value of type `T` from `io`, in canonical binary representation.

Note that Julia does not convert the endianness for you. Use [`ntoh`](@ref) or [`ltoh`](@ref) for this purpose.

```
read(io::IO, String)
```

Read the entirety of `io`, as a `String` (see also [`readchomp`](@ref)).

# Examples

```jldoctest
julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, Char)
'J': ASCII/Unicode U+004A (category Lu: Letter, uppercase)

julia> io = IOBuffer("JuliaLang is a GitHub organization");

julia> read(io, String)
"JuliaLang is a GitHub organization"
```

---

```
read(filename::AbstractString)
```

Read the entire contents of a file as a `Vector{UInt8}`.

```
read(filename::AbstractString, String)
```

Read the entire contents of a file as a string.

```
read(filename::AbstractString, args...)
```

Open a file and read its contents. `args` is passed to `read`: this is equivalent to `open(io->read(io, args...), filename)`.

---

```
read(s::IO, nb=typemax(Int))
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

---

```
read(s::IOStream, nb::Integer; all=true)
```

Read at most `nb` bytes from `s`, returning a `Vector{UInt8}` of the bytes read.

If `all` is `true` (the default), this function will block repeatedly trying to read all requested bytes, until an error or end-of-file occurs. If `all` is `false`, at most one `read` call is performed, and the amount of data returned is device-dependent. Note that not all stream types support the `all` option.

---

```
read(command::Cmd)
```

Run `command` and return the resulting output as an array of bytes.

---

```
read(command::Cmd, String)
```

Run `command` and return the resulting output as a `String`.


In [16]:
read("file.txt")

17-element Vector{UInt8}:
 0x61
 0x62
 0x63
 0x2c
 0x20
 0x64
 0x65
 0x66
 0x0a
 0x67
 0x68
 0x69
 0x2c
 0x20
 0x6a
 0x6b
 0x6c

In [17]:
readline("file.txt")

"abc, def"

In [18]:
using DelimitedFiles
readdlm("file.txt", ',')

2×2 Matrix{Any}:
 "abc"  " def"
 "ghi"  " jkl"

In [19]:
print("hello")
print("hello")

hellohello

In [20]:
println("hello")
println("hello")

hello
hello


In [21]:
show("hello")

"hello"

In [22]:
write("file.txt", "hello")

5

In [23]:
?parse()

```
parse(type, str; base)
```

Parse a string as a number. For `Integer` types, a base can be specified (the default is 10). For floating-point types, the string is parsed as a decimal floating-point number.  `Complex` types are parsed from decimal strings of the form `"R±Iim"` as a `Complex(R,I)` of the requested type; `"i"` or `"j"` can also be used instead of `"im"`, and `"R"` or `"Iim"` are also permitted. If the string does not contain a valid number, an error is raised.

!!! compat "Julia 1.1"
    `parse(Bool, str)` requires at least Julia 1.1.


# Examples

```jldoctest
julia> parse(Int, "1234")
1234

julia> parse(Int, "1234", base = 5)
194

julia> parse(Int, "afc", base = 16)
2812

julia> parse(Float64, "1.2e-3")
0.0012

julia> parse(Complex{Float64}, "3.2e-1 + 4.5im")
0.32 + 4.5im
```

---

```
parse(::Type{Platform}, triplet::AbstractString)
```

Parses a string platform triplet back into a `Platform` object.

---

```
parse(::Type{SimpleColor}, rgb::String)
```

An analogue of `tryparse(SimpleColor, rgb::String)` (which see), that raises an error instead of returning `nothing`.


In [24]:
parse(Int, "4153", base = 6)

933

In [25]:
parse(Bool, "1")

true

In [26]:
1 + 1

2

In [29]:
"hello" * " goodbye"

"hello goodbye"

In [31]:
5 - (-9)

14

In [32]:
45 * 666.0

29970.0

In [33]:
6 / 2

3.0

In [34]:
5^7

78125

In [35]:
sqrt(81)

9.0

In [36]:
81^0.5

9.0

In [39]:
57 > 9

true

In [38]:
99 == 99

true

In [40]:
(75 == 75) && (0 != 1) || !(true == false)

true

In [42]:
v = [1, 2, 3]
m = [1 2; 3 4]

2×2 Matrix{Int64}:
 1  2
 3  4

In [43]:
v + v

3-element Vector{Int64}:
 2
 4
 6

In [44]:
m + m

2×2 Matrix{Int64}:
 2  4
 6  8

In [ ]:
dot(v, v)